### ISSUE TITLE
Progress bar issue

### ISSUE THREAD

**Issue by Henthor** [Pe8er/Playbox.widget#15]
Great work with this. Progress bar doesn't seem to work for me though. It simply doesn't appear when playing a song. I've also tried your Sidebar widget and dionmunk's "Now Playing" widget based on your script. There I only get a full white bar, but it doesn't show the song's progression. Running on osx sierra 10.12.4 with newest version of übersicht (1.1). Do you know what might cause this issue?

**Comment by Pe8er** [comment]
Hi there! Thank you for your kind words. What is your system region set to?

**Comment by Ickerday** [comment]
Hiya, I got the same problem; also using dionmunk's fork. 
I'm running the widget with übersicht 1.1 and macOS Sierra 10.12.5. My system region and language is set to Polish. 
I ran `osascript 'Library/Application Support/Übersicht/widgets/now-playing.widget/lib/getTrack.applescript'` command that both widgets get the metadata in index.coffee with repeatedly, and it does appear it's returning all the data it's supposed to.
The problem lies in the `243.200 @ 1.99,.606.002.807.617` bit  - after changing the commas in the decimal grouping separators to dots in the `Regional Preferences -> Advanced`  and refreshing the widget, the progress bar started to work - the command returns with the following format, which I assume is parsable `285.653 @ 22.468999862671`.

Below's what I did in the Preferences.

Before:
![Before](https://cloud.githubusercontent.com/assets/12597189/26321524/5dab6574-3f27-11e7-9257-218b004c2faf.png)
After:
![After](https://cloud.githubusercontent.com/assets/12597189/26321526/5dcba4ce-3f27-11e7-809f-82a9e1d84797.png)

I then reverted changes above, as I don't really need the bar to live. :P 

Hope I gave some insight on the problem! 
Cheers, 
Bartek

**Comment by Pe8er** [comment]
@Henthor @Ickerday I may have fixed this! Please download the newest version and let me know:

https://github.com/Pe8er/Playbox.widget/raw/master/Playbox.widget.zip

@Ickerday dzięki wielkie za skrinszoty 😄

**Comment by Ickerday** [comment]
Yup, seems to be fixed! Cheers!

![screen1](https://cloud.githubusercontent.com/assets/12597189/26441563/3eb15dac-4131-11e7-9c6e-b34f5211a4ef.png)


![screen2](https://cloud.githubusercontent.com/assets/12597189/26441554/2e4b8154-4131-11e7-8ab1-faa60c008a58.png)

@Pe8er no pewnie. :)
