### ISSUE TITLE
It doesn't work on my mac

### ISSUE THREAD

**Issue by kakyoliu** [Pe8er/Playbox.widget#21]
now-playing-widget-index-coffee:
"now-playing.widget/lib/Get Current Track.applescript:860:861: script error: 预期是±Ì¥Ô Ωµ»µ»，却找到Œ¥÷™µƒº«∫≈。 (-2741)
"
redraw — client.js:5457
(anonymous function) — client.js:5424
(anonymous function) — client.js:5867
callback — client.js:5054:126
(anonymous function) — client.js:4958
emit — client.js:112
onreadystatechange — client.js:5093

**Comment by Pe8er** [comment]
Wow, that looks odd! Let's see how can I help you… a few questions:

1. Can you paste the title of the song you're listening to and artist name?

2. Can you show me a screenshot of your System Preferences > Language & Region panel please?

**Comment by StarCloudes** [comment]
It occurs to me either. It just doesn’t show anything on my mac for both spotify and iTunes. Have any ideas why it happens? (p:I use chinese language on the mac. )

**Comment by Pe8er** [comment]
@StarCloudes can you paste the title of the song you're listening to and artist name?

**Comment by StarCloudes** [comment]
Hmm, I change my language to English on my mac and it works!

**Comment by Pe8er** [comment]
Yes, that is the problem. Chinese characters are breaking the widget. Please paste the title and artist of the song you're listening to.

**Comment by ziyunch** [comment]
Hi Pe8er, I found that this issue also occurs on most of classical music, as the title usually contains lots of symbols. One example is Anne-Sophie Mutter, Manfred Honeck & Berlin Philharmonic's Violin Concerto in A Minor, Op. 53, B. 108: I. Allegro ma non troppo - Quasi moderato.

**Comment by Pe8er** [comment]
@ziyunch Can you show me a screenshot of your System Preferences > Language & Region panel please?

FYI it works for me, most likely because I have the primary language set to English. Let's figure out if we can make it work with your language though.

**Comment by ziyunch** [comment]
My region is set to US and preferred language is English(US).

**Comment by Pe8er** [comment]
I just played what seems to be the exact same track as you from Apple Music and the widget worked for me:

![image](https://i.imgur.com/cI95p0l.png)

Can you tell me what exactly is happening on your end when you play this track?

**Comment by ziyunch** [comment]
@Pe8er 

Here is what it looks on my end. 
<img width="200" alt="screen shot 2017-10-27 at 13 19 59" src="https://user-images.githubusercontent.com/5696435/32116711-c0c65a10-bb19-11e7-83be-ad833b120857.png">

As I mentioned before, my region is set to US and preferred language is English(US). So there is nothing to do with the language.

I think this issue happens on those songs containing symbols in infos, so I tested a few more songs in Apple Music.

It does not work on most classical songs, I guess that is due to the colon symbol;
It does not work on all songs in Ed Sheeran's album ÷ (Deluxe);
It does not work on Aoife O'Donovan's song;
It failed on all the songs with Chinese, Japanese or Western Latin characters.

There is no issue with some other symbols like ! . *

Another thing which is worthy to mention is that once I add those song into the library, this issue is gone. So if you test the track by adding it into your library and play, you won't see the issue.

**Comment by Pe8er** [comment]
Oh, I see what is happening. I was under the impression that the widget wasn't working at all for you, but the problem is specifically related to the artwork.

Here's how it works: unless a song is in your library, the widget can't access the artwork on iTunes. You've observed that yourself. So, in such cases the widget searches for artwork on Last.fm.

I found that the widget wasn't encoding some characters properly and I tried to optimize it. Please see the attached test version and let me know what you find.

[Test Playbox.widget.zip](https://github.com/Pe8er/Playbox.widget/files/1423257/Test.Playbox.widget.zip)

One note: some albums are named differently on each platform, for example Stranger Things 2 OST:

- iTunes: Kyle Dixon & Michael Stein - Stranger Things 2 (A Netflix Original Series Soundtrack) [Deluxe]
- Last.fm: Kyle Dixon - Stranger Things 2 (A Netflix Original Series Soundtrack)

In situations like this, I'm afraid I don't have a good idea on how to allow the widget to match differing names without creating too many false positives.
