### ISSUE TITLE
Playbox not showing up?

### ISSUE THREAD

**Issue by xxJuiceboxx1** [Pe8er/Playbox.widget#6]
Running el capitan 10.11.5 and i'm not seeing the actually playbox anywhere on my screen. Any ideas why this is happening?

**Comment by reatgcr0wn** [comment]
Running el capitan 10.11.5 and the same problem has occurred.
'Playbox.widget/as/Get Current Track.applescript' gives me the error:
"Expected end of line, etc. but found identifier"

**Comment by xxJuiceboxx1** [comment]
I get an error on like 4172:71

"       return contentEl.innerHTML = error, console.error(implementation.id + ":", error), rendered=!1;"

**Comment by Corgi** [comment]
Getting the same issue as reatgcr0wn, "Expected end of line, etc. but found identifier".

**Comment by Pe8er** [comment]
Hmm, strange! Let's look into it.

1. Which version of Ubersicht are you guys running? The latest is 0.9 (40).
2. Can you please navigate to `Playbox.widget/as/`, open `Get Current Track.applescript` in Script Editor and run it? Try it when there is music playing (either Spotify or iTunes should be fine)

**Comment by xxJuiceboxx1** [comment]
I'm running the latest version of ubersicht and when manually doing it like the way you outlined i am getting the playbox widget, but the positioning is weird and the album artwork is not showing up

**Comment by Wes974** [comment]
I got the same problem. I'm running the latest version of Ubersicht (0.9 (40)). When I run `Get Current Track.applescript` in `Playbox.widget/as/` in the Script Editor I got this :

`"Hans Zimmer & Junkie XL ~ Is She with You? ~ Batman v Superman: Dawn of Justice (Original Motion Picture Soundtrack) [Deluxe Edition] ~ ☆☆☆☆☆ ~ 346,743011474609 ~ 2,400000095367 ~ NA"`

This was the music currently playing in iTunes.

**Comment by Wes974** [comment]
Ok I solved it xDDD
I opened the Debug Console of Ubersicht and saw this message :
`osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.`

 So by looking a bit, I've found this : https://helpx.adobe.com/archive/photoshop/photoshop-cs4-troubleshooting.pdf
And at page 7 (`Unit type conversion error | AppleScript | Photoshop | Mac OS X 10.6`) they say you got to update `Adobe Unit Types.osax` by doing this : 

> Solution 1: Update the Adobe Unit Types.osax to version 2.1.0.
1 Click this link to download the Adobe Unit Types.osax version 2.1.0 file.
2 Choose /Library/ScriptingAdditions.
3 Move the existing Adobe Unit Types.osax file to a backup location.
4 Copy the downloaded version of the Adobe Unit Types.osax file to the /Library/ScriptingAdditions folder. Select Yes to authenticate this operation.
5 Restart your computer.

So I did, and it still didn't work, but when I looked the Debug Console again the message wasn't the same, it changed the `Adobe Unit Types.osax` to `QXPScriptingAdditions.osax`,so I just put it in the trash and done it was fixed. So maybe people should try this for fixing the problem.

**Comment by Corgi** [comment]
Running .9 Ubersicht. I found if I manually removed this section

```
else if musicapp is "Spotify" then
			tell application "Spotify"
				set {artistName, songName, albumName, rawRating, songDuration} to {artist, name, album, popularity, duration} of current track
				set currentPosition to my roundDown(player position as string)
			end tell
```

and ran the script while iTunes was playing, the widget appears on the desktop and I would get this output:

>"Death Cab for Cutie ~ Some Boys ~ Codes and Keys ~ ☆☆☆☆☆ ~ 190.772003173828 ~ 19.836999893188 ~ http://img2-ak.lst.fm/i/u/300x300/b5a3dddd36bd42668bdb5b11808efcfe.png"

Running the script as-is, it would ask me for the location of Spotify and then give me the previous error. I don't have Spotify installed at all, which seems like a likely reason for the issue.

**Comment by Pe8er** [comment]
> I don't have Spotify installed at all, which seems like a likely reason for the issue.

Yes, this is the problem. It seems like fixing it in Applescript is a little more convoluted than one may expect…I'm looking into it.

**Comment by Pe8er** [comment]
Update: I may have fixed it! Please download the latest version: https://github.com/Pe8er/Playbox.widget/blob/master/Playbox.widget.zip
